### PR TITLE
Various CSS fixes

### LINKED ISSUE #253: changelog page is too narrow, makes reading unpleasant

### PR DESCRIPTION
**Pull request by manyinsects**
Closes #253, #205, #392, and #387.

### CODE REVIEW

File: src/site/page/mod.rs [hunk 1]
```diff
@@ -71,7 +73,14 @@ impl Page {
     fn load_and_render_contents(source: &str, syntax_theme: &SyntaxTheme) -> Result<String> {
         let source = SourceFile::load_local(source)?;
         let contents = source.contents();
-        markdown::to_html(contents, syntax_theme)
+        markdown::to_html(contents, syntax_theme).map(|html| {
+            let html: Box<div<String>> = html!(
+                <div class="rendered-markdown">
```
Comment (ashleygwilliams) [inline src/site/page/mod.rs:78]: this is a great call

File: oranda-css/css/base.css [hunk 2]
```diff
@@ -178,7 +179,7 @@ blockquote {
 }
 
 main {
-  @apply mx-auto my-24 lg:max-w-3xl max-w-[80%];
+  @apply mx-auto my-24 lg:max-w-4xl max-w-[80%];
```
Comment (ashleygwilliams) [inline oranda-css/css/base.css:182]: i dont think i'm seeing this change on my screen width and i think it would be useful there - can you send a screen cap of what it looks like so i can compare?

Comment (manyinsects) [reply oranda-css/css/base.css:182]: new:

CleanShot 2023-06-19 at 15 29 22@2x

old:

CleanShot 2023-06-19 at 15 29 55@2x

Comment (ashleygwilliams) [reply oranda-css/css/base.css:182]: what width does it need to trigger this? (def looks better!)

Comment (manyinsects) [reply oranda-css/css/base.css:182]: i think the breakpoint is `lg`, which comes out to about 1024px

Comment (ashleygwilliams) [reply oranda-css/css/base.css:182]: i'm dumb and wasn't using the OCSS override. looks good

**Review by ashleygwilliams — APPROVED** [review]
