### PR TITLE
fix: check for file/folder existence before watching

### LINKED ISSUE #341: `oranda dev` expects `oranda.json` to exist
This is due to how `notify` expects paths given to it to exist (which makes total sense). We should probably implement a `Path::exists` check for every path we pass to `notify`.

### PR DESCRIPTION
**Pull request by manyinsects**
Closes #341.

### CODE REVIEW

**Review by Gankra — APPROVED** [review]
It would be cool if we could detect the dirs getting created but that sounds like a lot more messy work for minimal benefit.

File: src/commands/dev.rs [hunk 1]
```diff
@@ -125,7 +125,9 @@ impl Dev {
 
         for path in paths_to_watch {
             let path = PathBuf::from(path);
-            watcher.watch(path.as_path(), notify::RecursiveMode::Recursive)?;
+            if path.exists() {
+                watcher.watch(path.as_path(), notify::RecursiveMode::Recursive)?;
+            }
```
Comment (ashleygwilliams) [inline src/commands/dev.rs:132]: do we want to give a message if it doesn't that helps explain what might be happening?

Comment (manyinsects) [reply src/commands/dev.rs:132]: not sure how helpful that would be, imagine you have a minimal oranda setup (no config file, no book, etc), and you immediately get like 3 warning log messages. since the user doesn't add these paths i think it's fine to silently ignore

Comment (ashleygwilliams) [reply src/commands/dev.rs:132]: ah, so i was not fully understanding what was happening here. now that i do - i can make my comment more specific, which is... do we warn/error if there are no paths being watched? (is it possible that no path can be watched?)

Comment (manyinsects) [reply src/commands/dev.rs:132]: yes, if the user doesn't even have a readme file, although i think oranda will error anyways in that case
