### PR TITLE
fix assorted paths

### LINKED ISSUE #148: Some things do not take path_prefix into account
- [ ] script tag always loads from root
- [ ] favicon always loads from root
- [ ] link in artifacts to view all is not taking path prefix into account

### LINKED ISSUE #156: downloads should be "install"
we probably want to let people configure this eventually but for the moment i think install makes more sense

### PR DESCRIPTION
**Pull request by SaraVieira**
closes https://github.com/axodotdev/oranda/issues/148

### CODE REVIEW

File: src/site/path.rs [hunk 1]
```diff
@@ -0,0 +1,7 @@
+pub fn generate_prefix_link(path_prefix: &Option<String>, file_name: String) -> String {
```
Comment (ashleygwilliams) [inline src/site/path.rs]: since this does not always generate a link with a prefix should this just be generate? and since the only thing this does is build a link right now.. shall we call it link?

**Review by ashleygwilliams — CHANGES_REQUESTED** [review]

File: src/site/layout/header.rs [hunk 2]
```diff
@@ -42,15 +43,15 @@ fn nav(
...
 
         html.extend(html!(<li><a href=href>{text!(file_name)}</a></li>));
     }
 
     if let Some(artifact) = artifacts {
         if artifact.cargo_dist.is_some() {
-            let href = generate_prefix_link(path_prefix, String::from("artifacts"));
-            html.extend(html!(<li><a href=href>{text!("Downloads")}</a></li>));
+            let href = path::generate_prefix_link(path_prefix, String::from("artifacts.html"));
+            html.extend(html!(<li><a href=href>{text!("Install")}</a></li>));
```
Comment (SaraVieira) [inline src/site/layout/header.rs:54]: closes #156

File: src/site/path.rs (hunk 1 above)
Comment (SaraVieira) [reply src/site/path.rs]: hmm? I think you had a train of thought I couldn't follow :/

Comment (ashleygwilliams) [reply src/site/path.rs]: the function generates the link regardless of if it is prefixed or not, so i think it should be called generate link not generate prefix link.
this file is called path. it has a single function called generate_link so i think it should be called link not path.
the module should be called link, and so the function name should be just generate (or build?)

Comment (SaraVieira) [reply src/site/path.rs]: OHHH, update the file to be `link.rs` and the fn to be generate_link

File: src/site/link.rs [hunk 3]
```diff
@@ -0,0 +1,7 @@
+pub fn generate_link(path_prefix: &Option<String>, file_name: String) -> String {
```
Comment (ashleygwilliams) [inline src/site/link.rs]: any reason to keep "link" here?

Comment (SaraVieira) [reply src/site/link.rs]: fair question, removing

Comment (SaraVieira) [reply src/site/link.rs]: done

**Review by ashleygwilliams — APPROVED** [review]
